-- System-wide Task Template (WBS) tables

create table if not exists public.task_templates (
  id uuid primary key default gen_random_uuid(),
  template_no bigint generated by default as identity unique,
  name text not null,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.task_template_items (
  id uuid primary key default gen_random_uuid(),
  template_id uuid not null references public.task_templates(id) on delete cascade,
  wbs text not null,
  parent_wbs text not null default '',
  level int not null default 0,
  sort_order numeric(12,4) not null default 0,
  task_name text not null,
  duration int not null default 0,
  effort_manday numeric(12,3) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_task_template_items_template_sort
  on public.task_template_items(template_id, sort_order);

create index if not exists idx_task_template_items_template_parent
  on public.task_template_items(template_id, parent_wbs);

-- Keep updated_at fresh
create or replace function public.touch_task_templates_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_task_templates_updated_at on public.task_templates;
create trigger trg_touch_task_templates_updated_at
before update on public.task_templates
for each row
execute function public.touch_task_templates_updated_at();

alter table public.task_templates enable row level security;
alter table public.task_template_items enable row level security;

-- Read access for authenticated users
create policy if not exists task_templates_select_authenticated
on public.task_templates
for select
to authenticated
using (true);

create policy if not exists task_template_items_select_authenticated
on public.task_template_items
for select
to authenticated
using (true);

-- Admin-only create/update/delete
create policy if not exists task_templates_admin_insert
on public.task_templates
for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

create policy if not exists task_templates_admin_update
on public.task_templates
for update
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

create policy if not exists task_templates_admin_delete
on public.task_templates
for delete
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

create policy if not exists task_template_items_admin_insert
on public.task_template_items
for insert
to authenticated
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

create policy if not exists task_template_items_admin_update
on public.task_template_items
for update
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

create policy if not exists task_template_items_admin_delete
on public.task_template_items
for delete
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);
